spring.application.name=portfolio-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#Sur MAC, mettre le nom de l'ordinateur - Sur Win, mettre postgre
spring.datasource.username=nabjam
spring.datasource.password=nabjam

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.default-flat-param-object=true

#Clé 32 caractères minimum sinon JWT refuse
security.jwt.secret=${JWT_SECRET:my-super-secret-key-my-super-secret-key}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# environnement prod : false
app.seed-admin.enabled=false

# environnement dév: (supprimer la ligne pour l'envoie prod)
spring.profiles.active=dev

# =========================
# CONTACT / SMTP
# =========================
# À qui tu veux recevoir les messages (ta boîte)
#app.contact.to=${CONTACT_TO:contact@alexandredumont.dev}
#app.contact.to=contact@alexandredumont.dev

# "From" technique (souvent doit être le compte SMTP)
#app.contact.from=${CONTACT_FROM:${spring.mail.username:no-reply@portfolio.dev}}
#app.contact.from=no-reply@localhost.localdomain

# Timeout (optionnel)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# DEV SMTP (MailHog)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Contact addresses
app.contact.from=no-reply@localhost.localdomain
app.contact.to=contact@alexandredumont.dev